### ISSUE TITLE
NAAAB - Algorithm Week 1

### ISSUE THREAD

**Issue by LeNgocVanAnh** [kenneth-bui/algorithm-solving#4]
1. Choosing Numbers
2. Max Switching Slice
3. Dice Roll

[NAAAB_Codilitty_Questions.docx](https://github.com/user-attachments/files/16007447/NAAAB_Codilitty_Questions.docx)

**Comment by kenneth-bui** [comment]
Done

**Comment by LeNgocVanAnh** [comment]
Done
